CREATE TABLE AUTOR
(
    ID              INT          NOT NULL AUTO_INCREMENT,
    TXT_NOME        VARCHAR(200) NOT NULL,
    TXT_TELEFONE    VARCHAR(200) NOT NULL,
    DATA_NASCIMENTO DATE         NOT NULL,
    CONSTRAINT PK_AUTOR PRIMARY KEY (ID)
);